name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install kivy
          pip install requests
          pip install avwx-engine
          pip install airportsdata
          pip install airports-py

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: |
          sdkmanager --licenses
          sdkmanager "build-tools;37.0.0"

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Build APK
        run: |
          buildozer init
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
